// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "测试 Index 页",
                "tags": [
                    "测试"
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"gcp\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/count/all": {
            "post": {
                "description": "返回所有文档数目",
                "tags": [
                    "测试"
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"gcp\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/es/create/mytype": {
            "post": {
                "description": "创建es索引",
                "tags": [
                    "template"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "intvalue",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"创建成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "{\"success\": false, \"message\": \"该ID已存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"success\": false, \"message\": \"创建错误500\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/es/get/author": {
            "post": {
                "description": "获取es作者",
                "tags": [
                    "elasticsearch"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"该ID不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"success\": false, \"message\": \"错误500\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/es/get/conference": {
            "post": {
                "description": "获取es会议详细信息",
                "tags": [
                    "elasticsearch"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": 会议ID不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"success\": false, \"message\": \"错误500\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/es/get/journal": {
            "post": {
                "description": "获取es期刊详细信息",
                "tags": [
                    "elasticsearch"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": 期刊ID不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"success\": false, \"message\": \"错误500\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/es/get/mytype": {
            "post": {
                "description": "获取es索引",
                "tags": [
                    "template"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"该ID不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"success\": false, \"message\": \"错误500\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/es/get/paper": {
            "post": {
                "description": "es获取Paper详细信息",
                "tags": [
                    "elasticsearch"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"该PaperID不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"success\": false, \"message\": \"错误500\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/es/query/author/name": {
            "post": {
                "description": "es 根据姓名查询作者：精确查询,is_precise=0 为模糊匹配，为1为精准匹配",
                "tags": [
                    "elasticsearch"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "is_precise",
                        "name": "is_precise",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"获取作者成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"作者不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"success\": false, \"message\": \"错误500\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/es/query/paper/advanced": {
            "post": {
                "description": "es 高级搜索",
                "tags": [
                    "elasticsearch"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "musts",
                        "name": "musts",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "nots",
                        "name": "nots",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ors 至少是其中之一",
                        "name": "ors",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "min_year",
                        "name": "min_year",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "max_year",
                        "name": "max_year",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "size",
                        "name": "size",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "{\"success\": false, \"message\": \"参数错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"论文不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"success\": false, \"message\": \"错误500\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/es/query/paper/affiliation_name": {
            "post": {
                "description": "es 根据作者姓名查询文献：精确查询,is_precise=0 为模糊匹配，为1为精准匹配",
                "tags": [
                    "elasticsearch"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "affiliation_name",
                        "name": "affiliation_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "is_precise",
                        "name": "is_precise",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"获取作者成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"作者不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"success\": false, \"message\": \"错误500\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/es/query/paper/author_name": {
            "post": {
                "description": "es 根据作者姓名查询文献：精确查询,is_precise=0 为模糊匹配，为1为精准匹配",
                "tags": [
                    "elasticsearch"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "author_name",
                        "name": "author_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "is_precise",
                        "name": "is_precise",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"获取作者成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"作者不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"success\": false, \"message\": \"错误500\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/es/query/paper/doi": {
            "post": {
                "description": "es doi查询论文 精确搜索，结果要么有要么没有",
                "tags": [
                    "elasticsearch"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "doi",
                        "name": "doi",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"论文不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"success\": false, \"message\": \"错误500\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/es/query/paper/publisher": {
            "post": {
                "description": "es 根据出版商查询文献：精确查询,is_precise=0 为模糊匹配，为1为精准匹配",
                "tags": [
                    "elasticsearch"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "publisher",
                        "name": "publisher",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "is_precise",
                        "name": "is_precise",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"获取作者成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"作者不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"success\": false, \"message\": \"错误500\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/es/query/paper/title": {
            "post": {
                "description": "es 根据title查询论文",
                "tags": [
                    "elasticsearch"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "title",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "title",
                        "name": "page",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "{\"success\": false, \"message\": \"page 不是整数\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"论文不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"success\": false, \"message\": \"错误500\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/es/select/paper/title": {
            "post": {
                "description": "es 根据title筛选论文，包括对文章类型journal的筛选，页数的更换,页面大小size的设计, \\n 错误码：401 参数格式错误, 排序方式1为默认，2为引用率，3为年份",
                "tags": [
                    "elasticsearch"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "title",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "size",
                        "name": "size",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "min_year",
                        "name": "min_year",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "max_year",
                        "name": "max_year",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "doctypes",
                        "name": "doctypes",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "conferences",
                        "name": "conferences",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "journals",
                        "name": "journals",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "publishers",
                        "name": "publishers",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "sort_type",
                        "name": "sort_type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "sort_ascending",
                        "name": "sort_ascending",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "{\"success\": false, \"message\": \"page 不是整数\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"论文不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"success\": false, \"message\": \"错误500\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/es/update/mytype": {
            "post": {
                "description": "更新es索引",
                "tags": [
                    "template"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"更新成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"该ID不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"success\": false, \"message\": \"创建错误500\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/scholar/info": {
            "post": {
                "description": "获取学者信息",
                "tags": [
                    "学者门户"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user_id",
                        "name": "user_id",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "author_id",
                        "name": "author_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"用户验证邮箱成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "{\"success\": false, \"message\": \"userid 不是整数\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "402": {
                        "description": "{\"success\": false, \"message\": \"用户不是学者}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"用户不存在}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "600": {
                        "description": "{\"success\": false, \"message\": \"用户待修改，传入false 更新验证码，否则为验证正确}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/scholar/transfer": {
            "post": {
                "description": "学者添加或删除Paper,401 通常表示参数错误，Objw为被转让的人，当为添加或删除时，为零",
                "tags": [
                    "学者门户"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "user_id",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "obj_user_id",
                        "name": "obj_user_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "paper_id",
                        "name": "paper_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "0添加1删除2转让",
                        "name": "kind",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"用户验证邮箱成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "{\"success\": false, \"message\": \"用户已验证邮箱\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "402": {
                        "description": "{\"success\": false, \"message\": \"用户输入验证码错误}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"用户不存在}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "600": {
                        "description": "{\"success\": false, \"message\": \"用户待修改，传入false 更新验证码，否则为验证正确}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/social/collect/paper": {
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "收藏文献",
                "tags": [
                    "社交"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文献id",
                        "name": "paper_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "标签名称",
                        "name": "tag_name",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"收藏成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"success\": false, \"message\": \"用户未登录\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "{\"success\": false, \"message\": \"文献已收藏\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"用户ID不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/social/create/comment": {
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "创建评论",
                "tags": [
                    "社交"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文献id",
                        "name": "paper_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "评论内容",
                        "name": "content",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"评论创建成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"success\": false, \"message\": \"用户未登录\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "{\"success\": false, \"message\": \"评论创建失败\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"用户ID不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/social/create/tag": {
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "新建标签",
                "tags": [
                    "社交"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "标签名称",
                        "name": "tag_name",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"标签创建成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"success\": false, \"message\": \"用户未登录\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "402": {
                        "description": "{\"success\": false, \"message\": \"已创建该标签\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"用户ID不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/social/delete/collect/paper": {
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "取消文章收藏",
                "tags": [
                    "社交"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文献id",
                        "name": "paper_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"删除成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"success\": false, \"message\": \"用户未登录\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"用户ID不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/social/delete/tag": {
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "删除标签",
                "tags": [
                    "社交"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "标签名称",
                        "name": "tag_name",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"标签删除成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"success\": false, \"message\": \"用户未登录\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "{\"success\": false, \"message\": \"标签不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"用户ID不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/social/delete/tag/paper": {
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "删除某标签下的文章",
                "tags": [
                    "社交"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文献id",
                        "name": "paper_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "标签名称",
                        "name": "tag_name",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"删除成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"success\": false, \"message\": \"用户未登录\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"用户ID不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/social/get/all/collect": {
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "获取用户收藏的所有文献",
                "tags": [
                    "社交"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"查看文献成功\", \"data\": \"文章列表\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"success\": false, \"message\": \"用户未登录\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "402": {
                        "description": "{\"success\": false, \"message\": \"用户无收藏文章\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"用户ID不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/social/get/comments": {
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "获取文献所有评论，时间倒序",
                "tags": [
                    "社交"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文献id",
                        "name": "paper_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"查找成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "{\"success\": false, \"message\": \"评论不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/social/get/replies": {
            "post": {
                "description": "获取某条评论的回复",
                "tags": [
                    "社交"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "评论id",
                        "name": "comment_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"查找成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "{\"success\": false, \"message\": \"回复不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/social/get/tag/paper": {
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "查看用户标签的文章列表",
                "tags": [
                    "社交"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "标签名称",
                        "name": "tag_name",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"查看文献成功\", \"data\": \"标签下的文章列表\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"success\": false, \"message\": \"用户未登录\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "402": {
                        "description": "{\"success\": false, \"message\": \"标签下没有文章\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"用户ID不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/social/get/tags": {
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "查看用户所有标签",
                "tags": [
                    "社交"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"查看用户标签成功\", \"data\": \"model.User的所有标签\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"success\": false, \"message\": \"用户未登录\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "{\"success\": false, \"message\": \"未查询到结果\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"用户ID不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/social/like/cancel": {
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "取消点赞",
                "tags": [
                    "社交"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "评论id",
                        "name": "comment_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"操作成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "{\"success\": false, \"message\": \"用户未点赞\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/social/like/comment": {
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "点赞评论",
                "tags": [
                    "社交"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "评论id",
                        "name": "comment_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"操作成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "{\"success\": false, \"message\": \"评论不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/social/reply/comment": {
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "回复评论",
                "tags": [
                    "社交"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "评论id",
                        "name": "comment_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "回复内容",
                        "name": "content",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"回复成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"success\": false, \"message\": \"用户未登录\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"用户ID不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/submit/check": {
            "post": {
                "description": "用户申请创建，401 402 用户id，提交id不是正整数，404提交不存在，405 用户不存在",
                "tags": [
                    "管理员"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "提交id",
                        "name": "submit_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "success",
                        "name": "success",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "content",
                        "name": "content",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"创建成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/submit/create": {
            "post": {
                "description": "用户申请创建，402 用户id不是正忽视，404用户不存在，401 申请创建失败。后端炸了，405！！！该作者已被成功认领,并直接返回认领了该作者的学者姓名，406 该用户已经提交过对该学者的认领",
                "tags": [
                    "管理员"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "作者姓名",
                        "name": "author_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "机构姓名",
                        "name": "affiliation_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "工作邮箱",
                        "name": "work_email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "领域",
                        "name": "fields",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "主页",
                        "name": "home_page",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "作者id",
                        "name": "author_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"创建成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/submit/get/papers": {
            "post": {
                "description": "根据作者姓名返回姓名相近的作者并返回文献组",
                "tags": [
                    "管理员"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "author_name",
                        "name": "author_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "size",
                        "name": "size",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"创建成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/submit/list": {
            "post": {
                "description": "列举出所有type类型的submit，0表示未审批的，1表示审批成功的，2表示审批失败的",
                "tags": [
                    "管理员"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "提交id",
                        "name": "type",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/confirm": {
            "post": {
                "description": "验证邮箱",
                "tags": [
                    "用户管理"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "confirm_number",
                        "name": "confirm_number",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"用户验证邮箱成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "{\"success\": false, \"message\": \"用户已验证邮箱\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "402": {
                        "description": "{\"success\": false, \"message\": \"用户输入验证码错误}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"用户不存在}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "600": {
                        "description": "{\"success\": false, \"message\": \"用户待修改，传入false 更新验证码，否则为验证正确}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/info": {
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "查看用户个人信息",
                "tags": [
                    "用户管理"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"查看用户信息成功\", \"data\": \"model.User的所有信息\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"用户ID不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "登录",
                "tags": [
                    "用户管理"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "用户邮箱",
                        "name": "email",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"登录成功\", \"detail\": user的信息}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "{\"success\": false, \"message\": \"没有该用户\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "402": {
                        "description": "{\"success\": false, \"message\": \"密码错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/modify": {
            "post": {
                "security": [
                    {
                        "Authorization": []
                    }
                ],
                "description": "修改用户信息（支持修改用户名和密码）",
                "tags": [
                    "用户管理"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户个人信息",
                        "name": "user_info",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "原密码",
                        "name": "password_old",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "新密码",
                        "name": "password_new",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": true, \"message\": \"修改成功\", \"data\": \"model.User的所有信息\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "{\"success\": false, \"message\": \"用户未登录\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "{\"success\": false, \"message\": \"原密码输入错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "{\"success\": false, \"message\": \"用户ID不存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"success\": false, \"message\": \"数据库操作时的其他错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "注册",
                "tags": [
                    "用户管理"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户邮箱",
                        "name": "email",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\": false, \"message\": \"用户已存在\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{"https"},
	Title:       "Slime Scholar Golang Backend",
	Description: "hzh company",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
