info:
  contact: {}
  description: hzh company
  title: Slime Scholar Golang Backend
  version: "1.0"
paths:
  /:
    get:
      description: 测试 Index 页
      responses:
        "200":
          description: '{"success": true, "message": "gcp"}'
          schema:
            type: string
      tags:
      - 测试
  /count/all:
    post:
      description: 返回所有文档数目
      responses:
        "200":
          description: '{"success": true, "message": "gcp"}'
          schema:
            type: string
      tags:
      - 测试
  /es/create/mytype:
    post:
      description: 创建es索引
      parameters:
      - description: id
        in: formData
        name: id
        required: true
        type: string
      - description: intvalue
        in: formData
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "创建成功"}'
          schema:
            type: string
        "401":
          description: '{"success": false, "message": "该ID已存在"}'
          schema:
            type: string
        "500":
          description: '{"success": false, "message": "创建错误500"}'
          schema:
            type: string
      tags:
      - template
  /es/get/author:
    post:
      description: 获取es作者
      parameters:
      - description: id
        in: formData
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "获取成功"}'
          schema:
            type: string
        "404":
          description: '{"success": false, "message": "该ID不存在"}'
          schema:
            type: string
        "500":
          description: '{"success": false, "message": "错误500"}'
          schema:
            type: string
      tags:
      - elasticsearch
  /es/get/mytype:
    post:
      description: 获取es索引
      parameters:
      - description: id
        in: formData
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "获取成功"}'
          schema:
            type: string
        "404":
          description: '{"success": false, "message": "该ID不存在"}'
          schema:
            type: string
        "500":
          description: '{"success": false, "message": "错误500"}'
          schema:
            type: string
      tags:
      - template
  /es/get/paper:
    post:
      description: es获取Paper详细信息
      parameters:
      - description: id
        in: formData
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "获取成功"}'
          schema:
            type: string
        "404":
          description: '{"success": false, "message": "该PaperID不存在"}'
          schema:
            type: string
        "500":
          description: '{"success": false, "message": "错误500"}'
          schema:
            type: string
      tags:
      - elasticsearch
  /es/query/author/name:
    post:
      description: es 根据姓名查询作者：精确查询,isPrecise=0 为模糊匹配，为1为精准匹配
      parameters:
      - description: name
        in: formData
        name: name
        required: true
        type: string
      - description: isPrecise
        in: formData
        name: isPrecise
        type: integer
      responses:
        "200":
          description: '{"success": true, "message": "获取作者成功"}'
          schema:
            type: string
        "404":
          description: '{"success": false, "message": "作者不存在"}'
          schema:
            type: string
        "500":
          description: '{"success": false, "message": "错误500"}'
          schema:
            type: string
      tags:
      - elasticsearch
  /es/query/paper/doi:
    post:
      description: es doi查询论文 精确搜索，结果要么有要么没有
      parameters:
      - description: doi
        in: formData
        name: doi
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "获取成功"}'
          schema:
            type: string
        "404":
          description: '{"success": false, "message": "论文不存在"}'
          schema:
            type: string
        "500":
          description: '{"success": false, "message": "错误500"}'
          schema:
            type: string
      tags:
      - elasticsearch
  /es/query/paper/title:
    post:
      description: es 根据title查询论文
      parameters:
      - description: title
        in: formData
        name: title
        required: true
        type: string
      - description: title
        in: formData
        name: page
        required: true
        type: integer
      responses:
        "200":
          description: '{"success": true, "message": "获取成功"}'
          schema:
            type: string
        "401":
          description: '{"success": false, "message": "page 不是整数"}'
          schema:
            type: string
        "404":
          description: '{"success": false, "message": "论文不存在"}'
          schema:
            type: string
        "500":
          description: '{"success": false, "message": "错误500"}'
          schema:
            type: string
      tags:
      - elasticsearch
  /es/update/mytype:
    post:
      description: 更新es索引
      parameters:
      - description: id
        in: formData
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "更新成功"}'
          schema:
            type: string
        "404":
          description: '{"success": false, "message": "该ID不存在"}'
          schema:
            type: string
        "500":
          description: '{"success": false, "message": "创建错误500"}'
          schema:
            type: string
      tags:
      - template
  /social/collect/paper:
    post:
      description: 收藏文献
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        type: string
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      - description: id
        in: formData
        name: id
        required: true
        type: string
      - description: 标签名称
        in: formData
        name: tag_name
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "收藏成功"}'
          schema:
            type: string
        "400":
          description: '{"success": false, "message": "用户未登录"}'
          schema:
            type: string
        "404":
          description: '{"success": false, "message": "用户ID不存在"}'
          schema:
            type: string
      security:
      - Authorization: []
      tags:
      - 社交
  /social/create/comment:
    post:
      description: 创建评论
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        type: string
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      - description: id
        in: formData
        name: id
        required: true
        type: string
      - description: 评论内容
        in: formData
        name: content
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "评论创建成功"}'
          schema:
            type: string
        "400":
          description: '{"success": false, "message": "用户未登录"}'
          schema:
            type: string
        "403":
          description: '{"success": false, "message": "评论创建失败"}'
          schema:
            type: string
        "404":
          description: '{"success": false, "message": "用户ID不存在"}'
          schema:
            type: string
      security:
      - Authorization: []
      tags:
      - 社交
  /social/create/tag:
    post:
      description: 新建标签
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        type: string
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      - description: 标签名称
        in: formData
        name: tag_name
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "标签创建成功"}'
          schema:
            type: string
        "400":
          description: '{"success": false, "message": "用户未登录"}'
          schema:
            type: string
        "402":
          description: '{"success": false, "message": "已创建该标签"}'
          schema:
            type: string
        "404":
          description: '{"success": false, "message": "用户ID不存在"}'
          schema:
            type: string
      security:
      - Authorization: []
      tags:
      - 社交
  /social/delete/tag:
    post:
      description: 删除标签
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        type: string
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      - description: 标签名称
        in: formData
        name: tag_name
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "标签删除成功"}'
          schema:
            type: string
        "400":
          description: '{"success": false, "message": "用户未登录"}'
          schema:
            type: string
        "403":
          description: '{"success": false, "message": "标签不存在"}'
          schema:
            type: string
        "404":
          description: '{"success": false, "message": "用户ID不存在"}'
          schema:
            type: string
      security:
      - Authorization: []
      tags:
      - 社交
  /social/delete/tag/paper:
    post:
      description: 删除某标签下的文章
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        type: string
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      - description: id
        in: formData
        name: id
        required: true
        type: string
      - description: 标签名称
        in: formData
        name: tag_name
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "删除成功"}'
          schema:
            type: string
        "400":
          description: '{"success": false, "message": "用户未登录"}'
          schema:
            type: string
        "404":
          description: '{"success": false, "message": "用户ID不存在"}'
          schema:
            type: string
      security:
      - Authorization: []
      tags:
      - 社交
  /social/get/comments:
    post:
      description: 获取文献所有评论
      parameters:
      - description: 文献id
        in: formData
        name: paper_id
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "查找成功"}'
          schema:
            type: string
        "403":
          description: '{"success": false, "message": "评论不存在"}'
          schema:
            type: string
      tags:
      - 社交
  /social/get/replies:
    post:
      description: 获取某条评论的回复
      parameters:
      - description: 评论id
        in: formData
        name: comment_id
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "查找成功"}'
          schema:
            type: string
        "403":
          description: '{"success": false, "message": "回复不存在"}'
          schema:
            type: string
      tags:
      - 社交
  /social/get/tag/paper:
    post:
      description: 查看用户标签的文章列表
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        type: string
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      - description: 标签名称
        in: formData
        name: tag_name
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "查看文献成功", "data": "标签下的文章列表"}'
          schema:
            type: string
        "400":
          description: '{"success": false, "message": "用户未登录"}'
          schema:
            type: string
        "402":
          description: '{"success": false, "message": "标签下没有文章"}'
          schema:
            type: string
        "403":
          description: '{"success": false, "message": "用户未设置该标签"}'
          schema:
            type: string
        "404":
          description: '{"success": false, "message": "用户ID不存在"}'
          schema:
            type: string
      security:
      - Authorization: []
      tags:
      - 社交
  /social/get/tags:
    post:
      description: 查看用户所有标签
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        type: string
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "查看用户标签成功", "data": "model.User的所有标签"}'
          schema:
            type: string
        "400":
          description: '{"success": false, "message": "用户未登录"}'
          schema:
            type: string
        "403":
          description: '{"success": false, "message": "未查询到结果"}'
          schema:
            type: string
        "404":
          description: '{"success": false, "message": "用户ID不存在"}'
          schema:
            type: string
      security:
      - Authorization: []
      tags:
      - 社交
  /social/like/comment:
    post:
      description: 赞或踩评论
      parameters:
      - description: 评论id
        in: formData
        name: comment_id
        required: true
        type: string
      - description: 赞或踩,0-赞,1-踩
        in: formData
        name: option
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "操作成功"}'
          schema:
            type: string
        "403":
          description: '{"success": false, "message": "评论不存在"}'
          schema:
            type: string
      tags:
      - 社交
  /social/reply/comment:
    post:
      description: 回复评论
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        type: string
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      - description: 评论id
        in: formData
        name: comment_id
        required: true
        type: string
      - description: 回复内容
        in: formData
        name: content
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "回复成功"}'
          schema:
            type: string
        "400":
          description: '{"success": false, "message": "用户未登录"}'
          schema:
            type: string
        "404":
          description: '{"success": false, "message": "用户ID不存在"}'
          schema:
            type: string
      security:
      - Authorization: []
      tags:
      - 社交
  /user/confirm:
    post:
      description: 验证邮箱
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: confirm_number
        in: formData
        name: confirm_number
        required: true
        type: integer
      responses:
        "200":
          description: '{"success": true, "message": "用户验证邮箱成功"}'
          schema:
            type: string
        "401":
          description: '{"success": false, "message": "用户已验证邮箱"}'
          schema:
            type: string
        "402":
          description: '{"success": false, "message": "用户输入验证码错误}'
          schema:
            type: string
        "404":
          description: '{"success": false, "message": "用户不存在}'
          schema:
            type: string
        "600":
          description: '{"success": false, "message": "用户待修改，传入false 更新验证码，否则为验证正确}'
          schema:
            type: string
      tags:
      - 用户管理
  /user/info:
    post:
      description: 查看用户个人信息
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        type: string
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "查看用户信息成功", "data": "model.User的所有信息"}'
          schema:
            type: string
        "404":
          description: '{"success": false, "message": "用户ID不存在"}'
          schema:
            type: string
      security:
      - Authorization: []
      tags:
      - 用户管理
  /user/login:
    post:
      description: 登录
      parameters:
      - description: 用户名
        in: formData
        name: username
        type: string
      - description: 用户邮箱
        in: formData
        name: email
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "登录成功", "detail": user的信息}'
          schema:
            type: string
        "401":
          description: '{"success": false, "message": "没有该用户"}'
          schema:
            type: string
        "402":
          description: '{"success": false, "message": "密码错误"}'
          schema:
            type: string
      tags:
      - 用户管理
  /user/modify:
    post:
      description: 修改用户信息（支持修改用户名和密码）
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        type: string
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 用户个人信息
        in: formData
        name: user_info
        required: true
        type: string
      - description: 原密码
        in: formData
        name: password_old
        required: true
        type: string
      - description: 新密码
        in: formData
        name: password_new
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "修改成功", "data": "model.User的所有信息"}'
          schema:
            type: string
        "400":
          description: '{"success": false, "message": "用户未登录"}'
          schema:
            type: string
        "401":
          description: '{"success": false, "message": "原密码输入错误"}'
          schema:
            type: string
        "404":
          description: '{"success": false, "message": "用户ID不存在"}'
          schema:
            type: string
        "500":
          description: '{"success": false, "message": "数据库操作时的其他错误"}'
          schema:
            type: string
      security:
      - Authorization: []
      tags:
      - 用户管理
  /user/register:
    post:
      description: 注册
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 用户邮箱
        in: formData
        name: email
        type: string
      responses:
        "200":
          description: '{"success": false, "message": "用户已存在"}'
          schema:
            type: string
      tags:
      - 用户管理
schemes:
- https
swagger: "2.0"
